### ISSUE TITLE
Review animal behavior tutorial

### ISSUE THREAD

**Issue by jfberhane** [Bucknell-Biol364/Rtutorial#2]
https://github.com/Bucknell-Biol364/Rtutorial/blob/66bdf6660cc1c033f7921c5b7192eaf0ce11f95b/Rtutorial_anbe.R#L5

@KField-Bucknell @jssimpson20 @mnr006 @emilyjkonishi 

Hello! I think I'm done with the R script for the animal behavior tutorial. I was planning to check that it works on another computer tomorrow (I've only been using my laptop so far) so hopefully there are no bugs for you guys. But if there are, let me know! Thanks :)

**Comment by jssimpson20** [comment]
Hi Julie! I'll take a look at this today and give you comments this afternoon. Thank you!

**Comment by emilyjkonishi** [comment]
@jfberhane 
Hey Julie! I ran it on my mac and it worked well. Here are a few of my comments after reviewing your tutorial:

-Very descriptive and helpful instructions. You went into a lot of depth and were careful to make sure that a student who is first learning R will be able to understand what they are doing.
- The first code chunk in the data exploration part did not work when you typed in "Neuro_253_Cleaned_Data.csv" but did work when you typed in "Neuron_Recording_Data". You should change this part when you are telling them what data set to type into the code. 
-I like that you make them type in parts of their code in a template kind of format because it will help them learn better as it is more interactive then just making them run the code. 
-I understand why you  explained the importance of stacked data, but since it is not being used for this tutorial, they may disregard it. So maybe you should not even include it or you could just put a link up that will explain how the code works.

**Comment by mnr006** [comment]
Hey Julie and @ianvogel I went through both of your tutorials and was going to suggest some of the same ideas as Emily, but had a couple more:
-In our tutorial (208) we used special code for checking to see if a package was downloaded already and then loading it if it wasn't (this helps prevent errors that arise from redownloading the same package I believe).
-Also I'm using a very old pc which could be the issue, but I'm pretty sure cowplot is a package within itself so it needs to be loaded to be used (I was having some issues with it since I didn't have cowplot preloaded on my computer from previous use).
-Our group still needs to do this too, but cleaning up your REPO so it's not as difficult picking out what the user should be clicking on
-I believe we had issues knitting/compiling when we used the view() function, so you may want to consider replacing it with some other function

Other than that I thought it was awesome, and helpful not only as a tutorial but for future use that you can use to just plug your data and variables into! I really appreciated all the guidance as I went through. Obviously a lot of effort and thought went into how you would set these up, and it shows :)

**Comment by jfberhane** [comment]
@jssimpson20 @emilyjkonishi @mnr006 Thanks for all of your suggestions! I incorporated most if not all of them! :)
