### ISSUE TITLE
Neuro 253 tutorial ready for review

### ISSUE THREAD

**Issue by ianvogel** [Bucknell-Biol364/Rtutorial#4]
@cheyennelmoore @KateBille @emilyjkonishi

Hi Guys!

I think my neuro 253 version of our group's tutorial is ready for review. Please let me know if you run into issues accessing/running it. It is called Neuro_Rtutorial_final.r, if the r script version isn't working for some reason, try the rmarkdown that is just called Rtutorial.rmd.

Thanks!

**Comment by KateBille** [comment]
Hey Ian, I'll take a look at your stuff this afternoon and get back to you
with comments!

**Comment by cheyennelmoore** [comment]
Hey Ian, 
I just gave it a look. It looks great and you cover a lot. Here are some thoughts I had:
-label your code chunks that way students can communicate what chunks they're struggling with etc
-At line 125 the simple eda wouldn't work for me, but it worked at line 138
-The code chunk at line 172 is really big. I would split it up and encourage students to edit the chunks to get them to run with the iris data, then they would have running code to edit to test their hypotheses. Also you give them a lot of graphs which is great, but you may also way to consider only giving them a few and really focusing on what all the parts of the code mean and why they might want to use that graph. 
-To go along with the graphs maybe put one of the cheatsheets for picking graphs that Ken gave us in your repo for their reference. 

Overall, it's great, but also a lot. You do a great job of explaining  things so I think it should be okay, but don't forget it is there first time and being given code that already works is super helpful.

**Comment by KateBille** [comment]
Both tutorials look great. Below are my comments. Let me know if you need
clarification on anything.


1.       Code for setting the working directory: I thought this was a nifty
code but because you have them set their working directory via drop down
menus prior to this code chunk they will get an error message that the
working directory cannot be changed when they run the code chunk. I would
consider including only one way to set the working directory.


2.       Data exploration: the code chunk for checking head/tail and for
na’s did not work with Neuro_253_Cleaned_Data.csv but did work with
Neuron_Recording_Data. I really like that you have them type in their files!


3.       Stacked data: I think any code that is going to give them an error
message can be confusing. I like that you tell them about stacked data
though and why it is important when working in R. Maybe include a link to a
site explaining the code you used rather than providing the code that they
will not need. Using this function could also cause confusion later on when
they start working with the data.


4.       Summary statistics: again, I like that you are having them enter
their own file names as it gets them to “dig in” to the tutorial. I would
suggest telling them which variable to look at though (I used
Control_Spikes) that way the questions you ask at the bottom of the code
chunk are more meaningful.


5.       Since the goal of the initial code chunks simple.eda and
sphapiro.test is for them to understand how the functions work and what
information they provide, I would suggest which variables they should look
at so they can focus on those learning objectives rather than worrying
about which variable to look at.  Simple.eda also did not work for me
however I am on a PC in Academic West right now so that may be the issue. I
will try it again when I go over to Rooke this afternoon.



6.       For Rtutorial.Rmd: Line 217 you have a small typo “If we would
like to visualize the distribution of petal width values for three species then
this we can consult the KylaJacksonPlotTypes.png file” and line 231 “To
start it would be helpful to group the data based on the variables oyu are
most interested in.”. Line 271 “so that it knows not to treat the data as
two independent samples, and finally you ust specify the alternative
hypothesis as either”. Line 281 “a box plot depicting the difference betwee
pre and post drug administration”. Line 299 “You could potentiall pick a
different”


7.       As a general note you may want to give your code chunks meaningful
names. When I was making comments it would have been easier to use the name
of the code chunk name I was referencing. The students would probably find
this helpful as well when working through your tutorial.


8.        Overall I think these are both great tutorials. You were thorough
with your explanations and covered potential questions before they arose. I
also like that each tutorial covered parametric and non-parametric tests in
different ways, but both included advice on where to learn more about when
to use them. Great job guys!
